version: '3.1'

services:
  web:
    build: .
    ports:
      - "7000:7000"
      - "7001:7001"
    links:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: #@StrongP455w0rd#